### ISSUE TITLE
BuiltInPlugin error 

### ISSUE THREAD

**Issue by hkjang** [scouter-project/scouter-plugin-server-influxdb#2]
influxdb http 연결 하려는데 아래와 같은 서버 오류가 나오네요. 
오류내용이 짧아서 정확하게 어떤 오류인지 잘 모르겠습니다;; 

확인 가능하실까요?

20161005 16:20:50 [BuiltInPlugin]scouter.plugin.server.influxdb.InfluxdbPlugin=>counter
20161005 16:20:50 Server Plugin Load Error
20161005 16:20:50 InfluxDB Agent UDP local.port=0

**Comment by gunlee01** [comment]
java agent option에서 _trace=true 로 세팅하고 재기동해보면 Load 시점에 stack trace가 찍힐겁니다.
거기서 오류를 확인해 보세요.
