### ISSUE TITLE
InfluxDB 오류 문의

### ISSUE THREAD

**Issue by nostalgia4891** [scouter-project/scouter-plugin-server-influxdb#3]
안녕하세요. Scouter - InfluxDB 연동 간 아래와 같은 오류가 발생하는데 도움을 받을 수 있을까요?

- 버전
Scouter Server : 0.4.22
InfluxDB : 1.1.1

- scouter.conf  
`ext_plugin_influxdb_enabled=true`
`ext_plugin_influxdb_measurement=counter`
`ext_plugin_influxdb_udp=false`
`ext_plugin_influxdb_udp_target_ip=12.34.56.78`
`ext_plugin_influxdb_udp_target_port=8089`
`ext_plugin_influxdb_http_target_ip=12.34.56.78`
`ext_plugin_influxdb_http_target_port=8086`
`ext_plugin_influxdb_dbName=scouterCounter`

- 오류내용
[BuiltInPlugin]scouter.plugin.server.influxdb.InfluxdbPlugin=>counter
Server Plugin Load Error
InfluxDB Agent UDP local.port=0
[G003] [Plugin invoke fail] class scouter.plugin.server.influxdb.InfluxdbPlugin public void scouter.plugin.server.influxdb.InfluxdbPlugin.counter(scouter.lang.pack.PerfCounterPack) java.lang.reflect.InvocationTargetException
[IFLX002] null  -  Scouter Server 종료 시 까지 반복

SERVERE: Batch could not be sent. Data will be lost
java.lang.RuntimeException: {"error":"retention policy not founr: default"}
...

- 기타 
InfluxDB 서비스 Start 이후 각 포트(8083,8086,8089)가 Listen 하고 있는것은 확인되나
InfluxDB 접속 후 select 명령 시 아무 데이터가 확인되지 않습니다.

**Comment by suvisheshs** [comment]
@nostalgia4891 can you tell how you fixed the issue ? facing the similar one connecting to influx from scouter server using http method

`ext_plugin_influxdb_enabled=true
ext_plugin_influxdb_measurement=counter
ext_plugin_influxdb_udp=false
ext_plugin_influxdb_http_target_ip=12.34.56.78
ext_plugin_influxdb_http_target_port=8086
ext_plugin_influxdb_http_retention_policy=default
ext_plugin_influxdb_dbName=scouterCounter
`
