### ISSUE TITLE
플러그인 measurement를 summery, counter등 다수로 설정이 가능한가요?

### ISSUE THREAD

**Issue by Neptunium1129** [scouter-project/scouter-plugin-server-influxdb#5]
설정값을 보면 counter 한개만 지정해놓은것을 확인하였습니다.
counter, xlog , summery 이렇게 설정 할 수는 없는건가요?

**Comment by gunlee01** [comment]
timeseries DB 특성상 counter 데이터가 적합하므로 counter를 전송하는 plugin 으로 개발되었습니다.
당분간 업데이트 계획은 없는데요 ^^

혹시 scouter plugin 개발에 관심 있으시면 summary 등을 추가할 수 있는 기능 개발을 contribution 해주셔도 좋습니다.

**Comment by Neptunium1129** [comment]
넵 감사합니다.
